### ISSUE TITLE
Duration does not seem to be reported correctly.

### ISSUE THREAD

**Issue by mjc** [zachallaun/req_telemetry#3]
Based on how [Finch](https://github.com/sneako/finch/blob/main/lib/finch/telemetry.ex#L267-L276) and other libraries record duration (by subtracting end time from start time, using erlang native monotonic time,) formatting the duration does not seem to be the correct thing to do.

We have some systems that use millisecond and some that use nanosecond, so what we are seeing is that the division produces incorrect results on some of our systems.

**Comment by zachallaun** [comment]
The formatting only occurs in the default logger; the actual emitted event includes a `:duration` which is the same end - start monotonic calculation that seems to be common elsewhere ([see here](https://github.com/zachallaun/req_telemetry/blob/main/lib/req_telemetry.ex#L337)).

I'd happily accept a PR that provides more granular formatting, perhaps reporting μs instead of ms below a certain threshold.

**Comment by mjc** [comment]
Ok, so I looked at the wrong piece of code initially. We are not using your logger.

 There's an inconsistency in how durations are set, compared to other libraries:
Finch does `end_time = System.monotonic_time()` and `req_telemetry` does `System.monotonic_time(:microsecond)`.

The result is that LiveDashboard reports 0.635ms when I attach a telemetry_metrics handler, rather than 635ms.  Switching to `System.monotonic_time()` corrects it.

I'll happily submit a PR or whatever else you'd need, but it's just a oneliner.

**Comment by zachallaun** [comment]
Okay, understood! Duration will now reported in `:native` time units (`System.monotonic_time()`), which is what LiveDashboard should be expecting. I'll release 0.0.3 momentarily.

**Comment by mjc** [comment]
FWIW it looks like specifying `:milliseconds` as the unit for the TelemetryMetric configuration might also make the right thing happen. However, using native still seems to be the de facto standard.

**Comment by zachallaun** [comment]
@mjc Yes, I'd prefer to use native units as it is indeed the standard. The [`System`](https://hexdocs.pm/elixir/1.14.3/System.html#module-time) docs also reference this -- use `System.monotonic_time()` to get native units and then `System.convert_time_unit(units, :native, :millisecond)` to convert to your desired resolution.

I'm going to close this issue as resolved for now, but please feel free to re-open it or any others if you run into any other funny business!
